module.exports = {
    plugins: ['chasevida'],
    env: {
        browser: true,
        es6: true,
        node: true
    },
    ecmaFeatures: {
        modules: true,
        jsx: true
    },
    rules: {
        'array-bracket-spacing': [2, 'never'],
        'brace-style': [2, 'stroustrup'],
        'camelcase': 2,
        'chasevida/spaces-in-parens': [1, 'never', { 'exceptions': ['!'] }],
        'comma-dangle': [2, 'never'],
        'computed-property-spacing': [2, 'never'],
        'consistent-return': 2,
        'consistent-this': [2, 'self'],
        'curly': [2, 'all'],
        'dot-notation': 1,
        'eol-last': 1,
        'eqeqeq': 2,
        'func-style': [2, 'expression'],
        'global-strict': 0,
        'handle-callback-err': 2,
        'indent': [2, 4],
        'new-cap': 1,
        'new-parens': 2,
        'no-array-constructor': 2,
        'no-console': 1,
        'no-constant-condition': 2,
        'no-else-return': 2,
        'no-empty': 2,
        'no-eq-null': 2,
        'no-eval': 2,
        'no-ex-assign': 2,
        'no-extend-native': [2, {'exceptions': ['Object']}],
        'no-lonely-if': 2,
        'no-loop-func': 2,
        'no-mixed-spaces-and-tabs': 2,
        'no-multi-spaces': [2],
        'no-native-reassign': 2,
        'no-new-object': 2,
        'no-new-wrappers': 2,
        'no-process-exit': 2,
        'no-redeclare': 2,
        'no-regex-spaces': 2,
        'no-return-assign': 2,
        'no-shadow': 2,
        'no-sparse-arrays': 2,
        'no-trailing-spaces': 1,
        'no-undef': 2,
        'no-underscore-dangle': 2,
        'no-unused-expressions': 2,
        'no-unused-vars': 2,
        'no-use-before-define': 2,
        'object-curly-spacing': [2, 'always'],
        'one-var': 0,
        'quotes': [2, 'single', 'avoid-escape'],
        'semi': [2, 'never'],
        'sort-vars': 0,
        'space-after-keywords': 2,
        'space-before-function-paren': [2, 'always'],
        'space-infix-ops': 2,
        'space-return-throw-case': 2,
        'space-unary-ops': [1, { 'words': true, 'nonwords': true }],
        'vars-on-top': 0,
        'yoda': [1, 'never']
    }
};
